---

name: devops pipeline python app

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set short SHA
        run: |
          echo "SHORT_SHA"=$(echo ${GITHUB_SHA} | cut -c1-7) >> $GITHUB_ENV
      - name: Build docker image
        run: |
          docker build -t ttala/devops-labx:${{ env.SHORT_SHA }} .
      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER.DOCKERHUB_NAME }}" --password-stdin
      - name: Push to Dockerhub
        run: |
          docker push ttala/devops-labx:${{ env.SHORT_SHA }}
